SELECT 
	CANDIDATOS.ID_CANDIDATO		--Person_ID. 
	,CANDIDATOS.CANDIDATO
	,CANDIDATOS.REQUISITION_NUMBER
	,CANDIDATOS.SOLICITUD_PUESTO
	,CANDIDATOS.FECHA_APLICACIÓN
	,CANDIDATOS.POSITION_ID
	,CANDIDATOS.PROFILE_ID
	,CANDIDATOS.REQUISITION_ID 	--Union con feedbacks.REQUISITION_ID.  Este campo en si es la requisición del puesto... la solicitud del candidato al puesto.
	,CANDIDATOS.CURRENT_PHASE_ID
	,CANDIDATOS.PROCESS_ID
	,CANDIDATOS.SUBMISSION_ID 	--Union con PROGRESO_HISTORICO.SUBJECT_ID.
							  	--Union con feedbacks.REQUISITION_ID.			
FROM
	(Select
		CANDIDATES.PERSON_ID 							ID_CANDIDATO
		,P_NAMES.FULL_NAME 								CANDIDATO
		,TO_CHAR(REQ_B.REQUISITION_NUMBER) 				REQUISITION_NUMBER
		,REQ_TL.TITLE 									SOLICITUD_PUESTO
		,TO_CHAR(SUBM.SUBMISSION_DATE, 'DD/MM/YYYY') 	FECHA_APLICACIÓN
		,REQ_B.POSITION_ID 								POSITION_ID
		,SUBM.PROFILE_ID 								PROFILE_ID
		,REQ_B.REQUISITION_ID 							REQUISITION_ID
		,REQ_B.CURRENT_PHASE_ID 						CURRENT_PHASE_ID
		,REQ_B.PROCESS_ID 								PROCESS_ID
		,SUBM.SUBMISSION_ID 							SUBMISSION_ID
	From
		IRC_CANDIDATES 				CANDIDATES
		,IRC_SUBMISSIONS 			SUBM				--Cada aplicacion de puesto. 
		,PER_PERSON_NAMES_F 		P_NAMES
		,IRC_REQUISITIONS_B 		REQ_B				--Caracteristicas del puesto que se aplica. 1 a 1 con submision. 
		,IRC_REQUISITIONS_TL 		REQ_TL				--Solo por el name. 
		
	Where
		SUBM.PERSON_ID = CANDIDATES.PERSON_ID
		And P_NAMES.PERSON_ID = CANDIDATES.PERSON_ID
		And Trunc(SYSDATE) Between P_NAMES.EFFECTIVE_START_DATE And P_NAMES.EFFECTIVE_END_DATE
		And REQ_B.REQUISITION_ID = SUBM.REQUISITION_ID
		And REQ_TL.REQUISITION_ID = REQ_B.REQUISITION_ID
		And REQ_TL.LANGUAGE = USERENV ('LANG')
		and P_NAMES.NAME_TYPE = 'GLOBAL'   --Este filtro si o si. Sino me aparece el nombre regional y global. 
) CANDIDATOS

WHERE 
	CANDIDATOS.ID_CANDIDATO 		= :pCandidatos
	AND CANDIDATOS.REQUISITION_ID 	= :pSolicitudPuesto