SELECT
	--HISTORICO_EV_ACC.SOURCE_OBJECT_ID
	HISTORICO_EV_ACC.SUBJECT_ID,       --Union con CANDIDATO.SUBMISSION_ID.
	HISTORICO_EV_ACC.PERSON_ID,
	(	SELECT 	MAX(FULL_NAME) 
		FROM 	PER_PERSON_NAMES_F 
		WHERE 	PERSON_ID = HISTORICO_EV_ACC.PERSON_ID 
				AND Trunc(SYSDATE) Between EFFECTIVE_START_DATE And EFFECTIVE_END_DATE
	 ) NOMBRE,
	HISTORICO_EV_ACC.PROCESS_ID,
	PROCESOS.NAME PROCESO,
	HISTORICO_EV_ACC.PHASE_ID,
	FASES.NAME FASE,
	HISTORICO_EV_ACC.ACTION_ID,
	ACCIONES.ACTION_NAME,
	HISTORICO_EV_ACC.STATE_ID,
	ESTADOS.NAME ESTADO,
	HISTORICO_EV_ACC.HISTORY_EVENT_ID,
	HISTORICO_EV_ACC.EVENT_TYPE_ID,
	EVENTOS.NAME EVENTO,
	TO_CHAR(HISTORICO_EV_ACC.EVENT_DATE, 'DD/MM/YYYY') FECHA_EVENTO,
	HISTORICO_EV_ACC.EVENT_DATE,
	HISTORICO_EV_ACC.ROUTING_STEP_ID
	--HISTORICO_EV_ACC.TRACE_LOG
FROM
	IRC_LC_HISTORY HISTORICO_EV_ACC 					--Historico de eventos y acciones. 

--Tenemos fases y cada fase tiene eventos -> 1 fase n eventos. 
LEFT JOIN IRC_PHASES_TL FASES ON (
	FASES.PHASE_ID = HISTORICO_EV_ACC.PHASE_ID
	AND FASES.LANGUAGE = 'E')

LEFT JOIN IRC_PROCESSES_TL PROCESOS ON (
	PROCESOS.PROCESS_ID = HISTORICO_EV_ACC.PROCESS_ID
	AND PROCESOS.LANGUAGE = 'E')
	
--Ver si borrar esta de acciones, no me traia nada:
LEFT JOIN IRC_LC_ACTIONS_TL ACCIONES ON (
	ACCIONES.ACTION_ID = HISTORICO_EV_ACC.ACTION_ID
	AND ACCIONES.LANGUAGE = 'E')
	
LEFT JOIN IRC_STATES_TL ESTADOS ON (
	ESTADOS.STATE_ID = HISTORICO_EV_ACC.STATE_ID		--Estados: preseleccionado, etc. 
	AND ESTADOS.LANGUAGE = 'E')
	
LEFT JOIN IRC_HIST_EVENT_TL EVENTOS ON (
	EVENTOS.EVENT_TYPE_ID = HISTORICO_EV_ACC.EVENT_TYPE_ID
	AND EVENTOS.LANGUAGE = 'E')

WHERE HISTORICO_EV_ACC.EVENT_TYPE_ID <> 111 AND HISTORICO_EV_ACC.EVENT_TYPE_ID <> 4	AND  HISTORICO_EV_ACC.EVENT_TYPE_ID <> 106	
--Excluimos estos eventos. Para esto ver Events_Code.sql.
		--106: Comentarios solicitados. 
		--4: Fase finalizada
		--111: Acción ejecutada automáticamente: {ACTION_NAME}
		--Estos 2 son los que sirven y solo los que se deberian mostrar:
			--6:Estado activado
			--3:Fase activada
order by HISTORICO_EV_ACC.EVENT_DATE  --Asi esta bien, estaba mal asi: ORDER BY HISTORICO_EV_ACC.HISTORY_EVENT_ID

