SELECT
	POSICION.OBJECT_ID
	,POSICION.PROFILE_ID
	,POSICION.RELATION_ID
	,POSICION.NAME
	,POSICION.JOB_ID
	,POSICION.JOB_FAMILY_ID
	,POSICION.JOB_FAMILY_NAME
	,CAPACIDADES.CONTENT_TYPE_ID
	,CAPACIDADES.CONTENT_TYPE_NAME
	,CAPACIDADES.CONTENT_ITEM_ID
	,CAPACIDADES.NAME1
	,CAPACIDADES.ITEM_TEXT_22
	--,TAB_GRADOS.GRADO
	,(
		SELECT HRL.RATING_LEVEL_CODE
		FROM HRT_RATING_LEVELS_B HRL
		WHERE HRL.RATING_LEVEL_ID =	CAPACIDADES.RATING_LEVEL_ID1
	)GRADO
	,DECODE(rownum,1,:pPorcentajeCompetencias,0) porcentaje
FROM
	(SELECT
		BASE_0.OBJECT_ID OBJECT_ID
		,BASE_0.PROFILE_ID PROFILE_ID
		,BASE_0.RELATION_ID RELATION_ID
		,BASE_1.POSITION_ID POSITION_ID
		,BASE_1_1.NAME NAME
		,BASE_1.JOB_ID JOB_ID
		,BASE_1_2.JOB_FAMILY_ID JOB_FAMILY_ID
		,BASE_1_3.JOB_FAMILY_NAME JOB_FAMILY_NAME
	FROM 
		HRT_PROFILE_RELATIONS BASE_0
		,HR_ALL_POSITIONS_F BASE_1
		,HR_ALL_POSITIONS_F_TL BASE_1_1
		,PER_JOBS_F BASE_1_2
		,PER_JOB_FAMILY_F_TL BASE_1_3
	WHERE
		BASE_1.POSITION_ID = BASE_0.OBJECT_ID
		AND BASE_1_1.POSITION_ID = BASE_1.POSITION_ID
		AND BASE_1_1.LANGUAGE = USERENV('LANG')
		AND SYSDATE Between BASE_1_1.EFFECTIVE_START_DATE and BASE_1_1.EFFECTIVE_END_DATE
		AND BASE_1_2.JOB_ID = BASE_1.JOB_ID
		AND BASE_1_3.JOB_FAMILY_ID = BASE_1_2.JOB_FAMILY_ID
		AND BASE_1_3.LANGUAGE = USERENV('LANG')
		AND SYSDATE Between BASE_1_3.EFFECTIVE_START_DATE and BASE_1_3.EFFECTIVE_END_DATE
	) POSICION,

	(SELECT
		BASE_0.PROFILE_ID PROFILE_ID
		,BASE_1.CONTENT_TYPE_ID CONTENT_TYPE_ID
		,BASE_1_2.CONTENT_TYPE_NAME CONTENT_TYPE_NAME
		,BASE_1.CONTENT_ITEM_ID CONTENT_ITEM_ID
		,BASE_1_1.NAME NAME1
		,BASE_1.CONTENT_VALUE_SET_ID CONTENT_VALUE_SET_ID
		,BASE_1.CONTENT_ITEM_CODE CONTENT_ITEM_CODE
		,BASE_1.RATING_MODEL_ID RATING_MODEL_ID
		,BASE_1.ITEM_TEXT_22 ITEM_TEXT_22
		,BASE_0.RATING_LEVEL_ID1
	FROM 
		HRT_PROFILE_ITEMS BASE_0
		,HRT_CONTENT_ITEMS_B BASE_1
		,HRT_CONTENT_ITEMS_TL BASE_1_1
		,HRT_CONTENT_TYPES_TL BASE_1_2
	WHERE
		BASE_1.CONTENT_ITEM_ID = BASE_0.CONTENT_ITEM_ID
		AND BASE_1_1.CONTENT_ITEM_ID = BASE_1.CONTENT_ITEM_ID
		And BASE_1_1.LANGUAGE = USERENV ('LANG')
		And BASE_0.CONTENT_TYPE_ID = 104 -- Competencias / Capacidades
		AND BASE_1_2.CONTENT_TYPE_ID = BASE_1.CONTENT_TYPE_ID
		And BASE_1_2.LANGUAGE = USERENV ('LANG')
	) CAPACIDADES,

(SELECT *
FROM (
	SELECT 
		FURWF.ROW_LOW_RANGE_OR_NAME
		,FUCIF.VALUE
		,FUC.BASE_USER_COLUMN_NAME
	FROM 
		FF_USER_TABLES FUT
		,FF_USER_ROWS_F FURWF
		,FF_USER_COLUMNS FUC
		,FF_USER_COLUMN_INSTANCES_F FUCIF
	WHERE 
		FUT.BASE_USER_TABLE_NAME = UPPER('TAB_Competencias_De_Perfiles') 
		AND FUT.USER_TABLE_ID = FURWF.USER_TABLE_ID 
		AND FUT.USER_TABLE_ID = FUC.USER_TABLE_ID 
		AND FUC.USER_COLUMN_ID = FUCIF.USER_COLUMN_ID 
		AND FURWF.USER_ROW_ID = FUCIF.USER_ROW_ID)
PIVOT
	(MAX(VALUE)	FOR BASE_USER_COLUMN_NAME IN 
	('CAPACIDAD' AS CAPACIDAD, 'GRADO' AS GRADO, 'NIVEL' AS NIVEL)) 

ORDER BY TO_NUMBER(ROW_LOW_RANGE_OR_NAME)
) TAB_GRADOS

WHERE
	POSICION.PROFILE_ID = CAPACIDADES.PROFILE_ID
	--And POSICION.OBJECT_ID = 2680
	And TAB_GRADOS.NIVEL(+) = POSICION.JOB_FAMILY_NAME
	And TAB_GRADOS.CAPACIDAD(+) = CAPACIDADES.NAME1