-- CALIFICACIÓN DEL TÍTULO

SELECT
	BASE_0_0.PERSON_ID
	,BASE_0.PROFILE_ID PROFILE_ID
	,BASE_1_1.NAME NIVEL
	,DECODE(BASE_1.ITEM_TEXT30_1,'Y','Culminado','N','No Culminado','','Sin Informar') ESTADO
	,BASE_1.ITEM_TEXT240_1 TÍTULO
	,BASE_2_4.JOB_FAMILY_NAME JOB_FAMILY_NAME
	,TAB_CAL.CALIFICACION
FROM
	IRC_CANDIDATES BASE_0_0
	,HRT_PROFILES_B BASE_0_0_1 
	
	,IRC_SUBMISSIONS BASE_0
	,IRC_REQUISITIONS_B BASE_0_1
	,HRT_PROFILE_ITEMS BASE_1
	,HRT_CONTENT_ITEMS_TL BASE_1_1
	,HRT_PROFILE_RELATIONS BASE_2
	,HR_ALL_POSITIONS_F BASE_2_1
	,HR_ALL_POSITIONS_F_TL BASE_2_2
	,PER_JOBS_F BASE_2_3
	,PER_JOB_FAMILY_F_TL BASE_2_4
	
	,(SELECT * 
		FROM (SELECT 
					FURWF.ROW_LOW_RANGE_OR_NAME
					,FUCIF.VALUE
					,FUC.BASE_USER_COLUMN_NAME
				FROM 
					FF_USER_TABLES FUT,
					FF_USER_ROWS_F FURWF,
					FF_USER_COLUMNS FUC, 
					FF_USER_COLUMN_INSTANCES_F FUCIF
				WHERE 
					FUT.BASE_USER_TABLE_NAME = UPPER('TAB_Cargo_Formacion_Calificacion') 
					AND FUT.USER_TABLE_ID = FURWF.USER_TABLE_ID AND FUT.USER_TABLE_ID = FUC.USER_TABLE_ID AND FUC.USER_COLUMN_ID = FUCIF.USER_COLUMN_ID 
					AND FURWF.USER_ROW_ID = FUCIF.USER_ROW_ID
				) PIVOT(MAX(VALUE) FOR BASE_USER_COLUMN_NAME IN ('NIVEL' AS NIVEL, 'FORMACION' AS FORMACION, 'CALIFICACION' AS CALIFICACION)) 
	ORDER BY TO_NUMBER(ROW_LOW_RANGE_OR_NAME)) TAB_CAL

WHERE
	BASE_0_0.PERSON_ID = BASE_0.PERSON_ID 
	AND BASE_0.PROFILE_ID = BASE_0_0_1.PROFILE_ID
	AND BASE_0_0_1.PROFILE_ID = BASE_1.PROFILE_ID

	
	AND BASE_0_1.REQUISITION_ID = BASE_0.REQUISITION_ID													--Ver si comentarlo.  
	--AND BASE_1.PROFILE_ID = BASE_0.PROFILE_ID

	AND BASE_1.CONTENT_TYPE_ID = 106 	
	--AND SECTION_ID = 300000005246951 --Sección Títulos del perfil
	
	AND BASE_1_1.CONTENT_ITEM_ID = BASE_1.CONTENT_ITEM_ID
	AND BASE_1_1.LANGUAGE = USERENV('LANG')
	AND BASE_2.OBJECT_ID = BASE_0_1.POSITION_ID
	AND BASE_2_1.POSITION_ID = BASE_2.OBJECT_ID
	AND BASE_2_2.POSITION_ID = BASE_2_1.POSITION_ID
	AND BASE_2_2.LANGUAGE = USERENV('LANG')
	AND trunc(SYSDATE) Between BASE_2_2.EFFECTIVE_START_DATE and BASE_2_2.EFFECTIVE_END_DATE			--O sin el trunc. 
	AND BASE_2_3.JOB_ID = BASE_2_1.JOB_ID
	AND BASE_2_4.JOB_FAMILY_ID = BASE_2_3.JOB_FAMILY_ID
	AND BASE_2_4.LANGUAGE = USERENV('LANG')
	AND trunc(SYSDATE) Between BASE_2_4.EFFECTIVE_START_DATE and BASE_2_4.EFFECTIVE_END_DATE			--O sin el trunc. 
	
	
	--AND trunc(SYSDATE) between BASE_1.DATE_FROM AND BASE_1.DATE_TO
	
	AND TAB_CAL.NIVEL = BASE_2_4.JOB_FAMILY_NAME   	--	o... AND TAB_CAL.NIVEL(+) = BASE_2_4.JOB_FAMILY_NAME
	AND TAB_CAL.FORMACION = BASE_1_1.NAME			--  o... AND TAB_CAL.FORMACION(+) = BASE_1_1.NAME