SELECT
	BASE_0.PROFILE_ID
	,BASE_0.CONTENT_TYPE_ID
	,BASE_1_2.CONTENT_TYPE_NAME
	,BASE_0.ATTRIBUTE3 TIPO_EXPERIENCIA
	,BASE_0.ATTRIBUTE1 DESCRIPCION_EXPERIENCIA
	--,ROUND(BASE_0.ITEM_NUMBER_1 / 12) || ' Años' "ANT_REQUERIDA"
	,FLOOR(MONTHS_BETWEEN(BASE_0.ITEM_DATE_2, BASE_0.ITEM_DATE_1) /12) || ' Años' EXPERIENCIA_POS
FROM 
	HRT_PROFILE_ITEMS BASE_0
	,HRT_CONTENT_TYPES_TL BASE_1_2
WHERE
	BASE_0.CONTENT_TYPE_ID = 117 -- Experiencia
	AND BASE_0.CONTENT_TYPE_ID = BASE_1_2.CONTENT_TYPE_ID
	And BASE_1_2.LANGUAGE = USERENV ('LANG')