SELECT
	BASE_0.OBJECT_ID
	,BASE_0.PROFILE_ID
	,BASE_0.RELATION_ID
	,BASE_1.POSITION_ID
	,BASE_1_1.NAME
	,BASE_1.JOB_ID
	,BASE_1_2.JOB_FAMILY_ID
	,BASE_1_3.JOB_FAMILY_NAME
FROM 
	HRT_PROFILE_RELATIONS BASE_0
	,HR_ALL_POSITIONS_F BASE_1
	,HR_ALL_POSITIONS_F_TL BASE_1_1
	,PER_JOBS_F BASE_1_2
	,PER_JOB_FAMILY_F_TL BASE_1_3
WHERE
	BASE_1.POSITION_ID = BASE_0.OBJECT_ID
	AND BASE_1_1.POSITION_ID = BASE_1.POSITION_ID
	AND BASE_1_1.LANGUAGE = USERENV('LANG')
	AND SYSDATE Between BASE_1_1.EFFECTIVE_START_DATE and BASE_1_1.EFFECTIVE_END_DATE
	AND BASE_1_2.JOB_ID = BASE_1.JOB_ID
	AND BASE_1_3.JOB_FAMILY_ID = BASE_1_2.JOB_FAMILY_ID
	AND BASE_1_3.LANGUAGE = USERENV('LANG')
	AND SYSDATE Between BASE_1_3.EFFECTIVE_START_DATE and BASE_1_3.EFFECTIVE_END_DATE