SELECT 
	CANDIDATOS.ID_CANDIDATO
	,CANDIDATOS.CANDIDATO
	,CANDIDATOS.REQUISITION_NUMBER
	,CANDIDATOS.SOLICITUD_PUESTO
	,CANDIDATOS.FECHA_APLICACIÓN
	,CANDIDATOS.POSITION_ID
	,CANDIDATOS.PROFILE_ID
	,CANDIDATOS.REQUISITION_ID
	,CANDIDATOS.NAT_ID_TYPE
	,CANDIDATOS.NAT_ID
	
FROM
	(Select
		BASE_0.PERSON_ID ID_CANDIDATO
		,BASE_0_1.FULL_NAME CANDIDATO
		,TO_CHAR(ALIAS_1_1.REQUISITION_NUMBER) REQUISITION_NUMBER
		,ALIAS_2.TITLE SOLICITUD_PUESTO
		,TO_CHAR(ALIAS_1.SUBMISSION_DATE, 'DD/MM/YYYY') FECHA_APLICACIÓN
		,ALIAS_1_1.POSITION_ID POSITION_ID
		,ALIAS_1.PROFILE_ID PROFILE_ID
		,ALIAS_1_1.REQUISITION_ID REQUISITION_ID
		,PNI.NATIONAL_IDENTIFIER_TYPE   NAT_ID_TYPE
		,PNI.NATIONAL_IDENTIFIER_NUMBER	NAT_ID
	From
		IRC_CANDIDATES BASE_0
		,IRC_SUBMISSIONS ALIAS_1
		,PER_PERSON_NAMES_F BASE_0_1
		,IRC_REQUISITIONS_B ALIAS_1_1
		,IRC_REQUISITIONS_TL ALIAS_2
		,PER_NATIONAL_IDENTIFIERS 	PNI
		
	Where
		ALIAS_1.PERSON_ID = BASE_0.PERSON_ID
		And BASE_0_1.PERSON_ID = BASE_0.PERSON_ID
		And Trunc(SYSDATE) Between BASE_0_1.EFFECTIVE_START_DATE And BASE_0_1.EFFECTIVE_END_DATE
		And ALIAS_1_1.REQUISITION_ID = ALIAS_1.REQUISITION_ID
		And ALIAS_2.REQUISITION_ID = ALIAS_1_1.REQUISITION_ID
		And ALIAS_2.LANGUAGE = USERENV ('LANG')
		And BASE_0_1.NAME_TYPE = 'GLOBAL' 
		AND PNI.PERSON_ID(+) = BASE_0.PERSON_ID
) CANDIDATOS

WHERE 
	CANDIDATOS.ID_CANDIDATO = :pCandidato
	AND CANDIDATOS.REQUISITION_ID = :pSolicitudPuesto