Select 
	distinct BASE_0_1.FULL_NAME
	,BASE_0.PERSON_ID 
From 
	IRC_CANDIDATES BASE_0
	,PER_PERSON_NAMES_F BASE_0_1
Where 
	BASE_0_1.PERSON_ID = BASE_0.PERSON_ID
	and Trunc(SYSDATE) Between BASE_0_1.EFFECTIVE_START_DATE and BASE_0_1.EFFECTIVE_END_DATE
	and BASE_0_1.NAME_TYPE = 'GLOBAL' --agregado para restringir los nombres locales del pais
	and BASE_0.PERSON_ID in (Select X.PERSON_ID From IRC_SUBMISSIONS X,IRC_REQUISITIONS_B X1
							 Where X1.REQUISITION_ID = X.REQUISITION_ID and X1.CURRENT_PHASE_ID = 5 GROUP BY X.PERSON_ID)