SELECT
	TAREAS.TASK_NAME,
	TAREAS.EJECUTOR,
	TAREAS.RESPONSABILIDAD,
	TAREAS.INICIO, 						--Estas 2 fechas (INICIO Y FIN) son las fechas cuando el empleado comenzó y finalizó el checklista/tareas de la lista. 
	TAREAS.FIN,
	TAREAS.ESTADO,
	to_char(EMPLEADO.ALLOCATION_DATE,'DD/MM/YYYY')  	as ALLOCATION_DATE, 	--Filtramos por :pFechaInicio y :pFechaFin: Esta es la Fecha que 
																				--se le ASIGNÓ al empleado el checklist/tareas de la lista a resolver. 
	EMPLEADO.PACHECK_TL_CHECKLIST_NAME,   	--Por esta lista de comprobacion filtramos en :pListas.
	EMPLEADO.PERSON_ID
	
FROM

	(SELECT
		PACHECK.ALLOCATED_CHECKLIST_ID
		,PACHECK_TL.CHECKLIST_NAME					PACHECK_TL_CHECKLIST_NAME
		,PACHECK_TL.DESCRIPTION
		,PACHECK_TL.MESSAGE_TITLE
		,PACHECK_TL.MESSAGE_TEXT
		,PACHECK_TL.CHECKLIST_DETAILS
		,PACHECK.LEGISLATION_CODE
		,PACHECK.CHECKLIST_ID
		,PACHECK.PERSON_ID
		,PAPF.PERSON_NUMBER
		,PACHECK.CHECKLIST_NAME
		,PACHECK.DESCRIPTION BASE0_DESCRIPTION
		,PACHECK.CHECKLIST_STATUS
		,PACHECK.ALLOCATION_DATE
		,PACHECK.COMPLETED_ON
		,PACHECK.ALLOCATION_DETAILS
	FROM
		PER_ALLOCATED_CHECKLISTS 		PACHECK
		,PER_ALLOCATED_CHECKLISTS_TL 	PACHECK_TL
		,PER_ALL_PEOPLE_F 				PAPF
	WHERE
		PACHECK.ALLOCATED_CHECKLIST_ID = PACHECK_TL.ALLOCATED_CHECKLIST_ID
		AND PACHECK_TL.LANGUAGE = USERENV ('LANG')
		AND PAPF.PERSON_ID = PACHECK.PERSON_ID 
		AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
		AND (PACHECK.ALLOCATION_DATE BETWEEN :pFechaInicio AND :pFechaFin)     --Fecha qe se le asigno al empleado el checklist de la lista a resolver.         
		AND ((COALESCE(null, :pListas) is null) OR (PACHECK_TL.CHECKLIST_NAME IN (:pListas)))
	) EMPLEADO,
	
	(SELECT
		-- PACHECK_TL.TASK_NAME TAREAS
		(	SELECT 	MAX(PACHECK_TL.TASK_NAME) 
			FROM 	PER_ALLOCATED_TASKS_TL PACHECK_TL 
			WHERE 	PACHECK_TL.ALLOCATED_TASK_ID = PATASKS.ALLOCATED_TASK_ID 
					AND PACHECK_TL.LANGUAGE = USERENV ('LANG') 
		) TASK_NAME
		,PATASKS.ALLOCATED_CHECKLIST_ID
		,CASE
		   WHEN PATASKS.STATUS = 'COM' THEN 'Completo'
		   WHEN PATASKS.STATUS = 'INI' THEN 'Pendiente'
		   WHEN PATASKS.STATUS = 'INP' THEN 'En Progreso'
		   WHEN PATASKS.STATUS = 'OUT' THEN 'Excepcional'
		   WHEN PATASKS.STATUS = 'REJ' THEN 'Rechazada'
		   WHEN PATASKS.STATUS = 'SUS' THEN 'Suspendida'
		   WHEN PATASKS.STATUS = 'WIT' THEN 'Retirada'
		   WHEN PATASKS.STATUS = 'WAI' THEN 'Diferido hasta la fecha'
		   WHEN PATASKS.STATUS = 'DEP' THEN 'Depende de otras tareas'
		   ELSE 'No Informa'
		END ESTADO
		,CASE
		   WHEN PATASKS.RESPONSIBILITY_TYPE = 'ORA_WORKER' THEN 'Empleado'
		   ELSE 'Área de responsabilidad'
		END EJECUTOR  --Quien tiene que realizar la tarea. 

		,CASE
		   WHEN PATASKS.RESPONSIBILITY_TYPE = 'ORA_WORKER' THEN ' '
		   WHEN PATASKS.RESPONSIBILITY_TYPE = 'USTA_TIC' THEN 'TIC'
		   WHEN PATASKS.RESPONSIBILITY_TYPE = 'ORA_NL_CASE_MANAGER' THEN 'Manager'
		   WHEN PATASKS.RESPONSIBILITY_TYPE = 'USTA_CONTRATACION' THEN 'Contratación'
		   ELSE 'Área de responsabilidad'
		END RESPONSABILIDAD
		,TO_CHAR(PATASKS.TARGET_START_DATE, 'DD/MM/YYYY') INICIO
		,TO_CHAR(PATASKS.TARGET_END_DATE, 'DD/MM/YYYY') FIN
	FROM
		PER_ALLOCATED_TASKS PATASKS
		-- ,PER_ALLOCATED_TASKS_TL PACHECK_TL
	WHERE
		-- PACHECK_TL.ALLOCATED_TASK_ID = PATASKS.ALLOCATED_TASK_ID
		-- AND PACHECK_TL.LANGUAGE = USERENV ('LANG')
		
		--Parametro Estado:
		((COALESCE(null, :pEstado) is null) OR (PATASKS.STATUS IN (:pEstado)))
		
		--Parametro Tareas:
		AND 
		((COALESCE(null, :pTareas) is null) OR (
		(	SELECT 	MAX(PACHECK_TL.TASK_NAME) 
			FROM 	PER_ALLOCATED_TASKS_TL PACHECK_TL 
			WHERE 	PACHECK_TL.ALLOCATED_TASK_ID = PATASKS.ALLOCATED_TASK_ID 
					AND PACHECK_TL.LANGUAGE = USERENV ('LANG') 
			)
		IN (:pTareas)))
		
	) TAREAS

WHERE
	EMPLEADO.ALLOCATED_CHECKLIST_ID = TAREAS.ALLOCATED_CHECKLIST_ID
	AND TAREAS.TASK_NAME NOT IN ('Antes del primer día', 'Actividades del primer día')