Select 
	distinct 
	PER_NAMES.FULL_NAME
	,CANDIDATOS.PERSON_ID 
From 
	IRC_CANDIDATES CANDIDATOS
	,PER_PERSON_NAMES_F PER_NAMES
Where 
	PER_NAMES.PERSON_ID = CANDIDATOS.PERSON_ID
	and Trunc(SYSDATE) Between PER_NAMES.EFFECTIVE_START_DATE and PER_NAMES.EFFECTIVE_END_DATE
	and CANDIDATOS.PERSON_ID in (	Select 	X.PERSON_ID 
									From 	IRC_SUBMISSIONS X,IRC_REQUISITIONS_B X1
									Where 	X1.REQUISITION_ID = X.REQUISITION_ID 
											and X1.CURRENT_PHASE_ID = 5 
											GROUP BY X.PERSON_ID
								)
	and PER_NAMES.NAME_TYPE = 'GLOBAL'   --Este filtro si o si. Sino me aparece el nombre regional y global. 
	order by PER_NAMES.FULL_NAME